# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Create Archive
        uses: ksm2/archive-action@v1
        with:
          format: zip
          name: python
      
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: python
          path: target/
        
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo "Python Installed"
    
